ALTER SESSION SET NLS_DATE_FORMAT ='DD/MM/YYYY HH24:MI:SS';

CREATE TABLE BTKHDL3.HANGHANGKHONG
(
    MAHANG VARCHAR2(2),
    TENHANG VARCHAR(30),
    NGTL DATE,
    DUONGBAY NUMBER,
    CONSTRAINT PK_HANG PRIMARY KEY (MAHANG)
)

CREATE TABLE BTKHDL3.CHUYENBAY
(
    MACB VARCHAR2(5),
    MAHANG VARCHAR2(2) REFERENCES BTKHDL3.HANGHANGKHONG(MAHANG),
    XUATPHAT VARCHAR2(30),
    DIEMDEN VARCHAR2(30),
    BATDAU DATE,
    TGBAY NUMBER,
    CONSTRAINT PK_CB PRIMARY KEY (MACB)
)

CREATE TABLE BTKHDL3.NHANVIEN
(
    MANV VARCHAR2(4),
    HOTEN VARCHAR2(30),
    GIOITINH VARCHAR2(5),
    NGSINH DATE,
    NGVL DATE,
    CHUYENMON VARCHAR2(20),
    CONSTRAINT PK_NV PRIMARY KEY (MANV)
)

CREATE TABLE BTKHDL3.PHANCONG
(
    MACB VARCHAR2(5) REFERENCES BTKHDL3.CHUYENBAY(MACB),
    MANV VARCHAR2(4) REFERENCES BTKHDL3.NHANVIEN(MANV),
    NHIEMVU VARCHAR2(20),
    CONSTRAINT PK_PHCONG PRIMARY KEY (MACB,MANV)
)

ALTER USER BTKHDL3 quota unlimited on USERS;
ALTER SESSION SET NLS_DATE_FORMAT ='DD/MM/YYYY HH24:MI:SS';
INSERT INTO BTKHDL3.HANGHANGKHONG VALUES('VN','Vietnam Airlines','15/01/1956', 52);
INSERT INTO BTKHDL3.HANGHANGKHONG VALUES('VJ', 'Vietjet Air', '25/12/2011', 33);
INSERT INTO BTKHDL3.HANGHANGKHONG VALUES('BL', 'Jetstar Pacific Airlines', '01/12/1990', 13);

INSERT INTO BTKHDL3.CHUYENBAY VALUES('VN550', 'VN', 'TP.HCM', 'Singapore', '20/12/2015 13:15', 2);
INSERT INTO BTKHDL3.CHUYENBAY VALUES('VJ331', 'VJ', '?a Nang', 'Vinh', '28/12/2015 22:30', 1);
INSERT INTO BTKHDL3.CHUYENBAY VALUES('BL696', 'BL', 'TP. HCM', 'Da Lat', '24/12/2015 06:00', 0.5);

INSERT INTO BTKHDL3.NHANVIEN VALUES('NV01', 'Lam Van Ben', 'Nam', '10/09/1978', '05/06/2000', 'Phi cong');
INSERT INTO BTKHDL3.NHANVIEN VALUES('NV02', 'Duong Thi Luc', 'Nu', '22/03/1989', '12/11/2013', 'Tiep vien');
INSERT INTO BTKHDL3.NHANVIEN VALUES('NV03', 'Hoang Thanh Tung','Nam', '29/07/1983', '11/04/2007', 'Tiep vien');

INSERT INTO BTKHDL3.PHANCONG VALUES('VN550', 'NV01' ,'Co truong');
INSERT INTO BTKHDL3.PHANCONG VALUES('VN550', 'NV02' ,'Tiep vien');
INSERT INTO BTKHDL3.PHANCONG VALUES('BL696', 'NV03' ,'Tiep vien truong');

select * from  BTKHDL3.PHANCONG

/*Cau 5*/
SELECT *
FROM BTKHDL3.NHANVIEN
WHERE EXTRACT(MONTH FROM (NGSINH)) = 7;

/*Cau 6*/
SELECT MACB, COUNT(MANV) AS "So nhan vien"
FROM BTKHDL3.PHANCONG 
GROUP BY MACB
HAVING COUNT(MANV) >= ALL(SELECT COUNT(MANV)
                        FROM BTKHDL3.PHANCONG 
                        GROUP BY MACB);
                        
/*Cau 7*/
SELECT MAHANG, COUNT(MACB) AS "So chuyen bay"
FROM BTKHDL3.CHUYENBAY
where MACB IN                   (SELECT BTKHDL3.PHANCONG.MACB
                                FROM BTKHDL3.PHANCONG
                                WHERE BTKHDL3.CHUYENBAY.MACB = BTKHDL3.PHANCONG.MACB
                                AND XUATPHAT = 'Da Nang'
                                GROUP BY BTKHDL3.PHANCONG.MACB
                                having count(MANV) >2)
GROUP BY MAHANG 

/*Cau 8*/
SELECT*
FROM BTKHDL3.NHANVIEN
WHERE NOT EXISTS( SELECT *
                FROM BTKHDL3.CHUYENBAY
                WHERE NOT EXISTS (SELECT *
                                FROM BTKHDL3.PHANCONG
                                WHERE BTKHDL3.CHUYENBAY.MACB = BTKHDL3.PHANCONG.MACB
                                AND BTKHDL3.PHANCONG.MANV = BTKHDL3.NHANVIEN.MANV))